config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :comments
  get '/posts/comment' => 'posts#save_comment'
  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', 
    confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base 
	extend FriendlyId 
	friendly_id :slug_candidates, use: [:slugged, :finders]
	#attr_accessor :slug
	acts_as_commentable class_name: 'Comment'
	acts_as_taggable
	acts_as_taggable_on :tag

	def slug_candidates
    [
      :title,
      [:title, :body],
    ]
  	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!
	def index
		@articles = Post.all
	end

	def new
		@article = Post.new
	end

	def create
		#authorize! :create, Post
		@article = Post.new(blog_params)
		#@article.slug = nil
		#d@article.slug = nil
		#@article.tag_list.add("awesome, slick")
		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def show
		#@article = Post.find(params[:id])
		@article = Post.friendly.find(params[:id])
		#@article = commentable
		@comments = @article.comments.all
		@tags = @article.tag
	end

	def save_comment
		comment_params
		commentable = Post.find(params[:article_id])
		@comment = commentable.comments.create
		@comment.title = params[:title]
		@comment.comment = params[:comment]
		if @comment.save
			redirect_to commentable
		else
			render 'show'
		end
	end

	def destroy
	  #authorize! :destroy, Post
	  @article = Post.find(params[:id])
	  authorize! :destroy, @article
	  @article.destroy
	  redirect_to posts_path
	end

	def edit
	  #authorize! :update, Post
	  @article = Post.friendly.find(params[:id])
	  authorize! :update, @article
	  @tags = @article.tag
	end

	def update
	  #authorize! :update, Post
	  @article = Post.find(params[:id])
	  authorize! :update, @article
	  if @article.update(blog_params)
	    redirect_to @article
	  else
	    render 'edit'
	  end
	end


	private
	def blog_params
		params.require(:article).permit(:title,:body,:tag_list,:user_id)
	end

	def comment_params
		params.require(:comment).permit(:article_id,:title,:comment,:user_id)
	end



end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= form_for :article, url: post_path(@article), method: :patch do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, :value => @article[:title] %>
  </p>
 
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body, :value => @article[:body] %>
  </p>
 
  <p>
    <%= f.label :tag_list %><br>
    <%= f.text_field :tag_list, :value => @tags.join(", ") %>
  </p>

  <%= f.hidden_field :user_id, :value => current_user.id %>
  
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing Articles</h1>
Welcome <%= current_user.email %><br/> 
<%= link_to 'New article', new_post_path %>
<%= link_to 'Logout', destroy_user_session_path, method: :delete %>



<% @articles.each do |article| %>
  <h2><%= link_to article.title, post_path(article) %></h2>
    By <code><%= User.find(article.user_id).email %> &nbsp;&nbsp; <%= link_to 'Edit', edit_post_path(article) %> &nbsp;&nbsp;
    <%= link_to 'Destroy', post_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></code><br/>
    <p>
      <%= article.body %>
    </p>
    <code> Tags: <%= article.tags.join(", ") %> </code>
<% end %>

app/views/posts/new.html.erb
<%= form_for :article, url: posts_path do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
 
  <p>
    <%= f.label :tag_list %><br>
    <%= f.text_field :tag_list %>
  </p>

  <%= f.hidden_field :user_id, :value => current_user.id %>
  
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/print_session.html.erb
<%= current_user.email %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<strong> Tags: </strong><br/>
<% @tags.each do |tag|  %>
   <p>
   		<%= tag %>
   </p>
<% end %>

<h2>Comments</h2>
<% @comments.each do |comment| %>
  <p>
  	<strong>Commenter</strong>
  	<%= User.find(comment.user_id).email %>
  </p>

  <p>
    <strong>Comment Title:</strong>
    <%= comment.title %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.comment %>
  </p>
<% end %>
 
<h2>Add a comment:</h2>
<%= form_for :comment, url: comments_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </p>
  <p>
  	 <%= f.hidden_field :commentable_id, :value => @article[:id] %>
  	 <%= f.hidden_field :commentable_type, :value => 'Post' %>
  	 <%= f.hidden_field :user_id, :value => current_user.id %>
  </p>
  <p>
    <%= f.submit %>
  </p>
 
<% end %>